apiVersion: v1
kind: Service
metadata:
  name: nexaops-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nexaops-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
